[package]
name = "metteur-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "metteur"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
crossterm.workspace = true
metteur-proto = { path = "../proto" }
ratatui.workspace = true
serde_json.workspace = true
tokio.workspace = true
tonic.workspace = true
uuid.workspace = true
zip.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_System_Console"] }
