[package]
name = "metteur-web-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "metteur-web"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
http.workspace = true
metteur-proto = { path = "../proto" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
tonic-web.workspace = true
tower.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true